version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=db_resep
      - DB_USER=postgres
      - DB_PASSWORD=password

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: db_resep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
